export const ShowTypes = {
  FETCH_SHOW: "show/FETCH_SHOW",
  FETCH_SHOW_SUCCEEDED: "show/FETCH_SHOW_SUCCEEDED",
  FETCH_SHOW_FAILED: "show/FETCH_SHOW_FAILED",

  FETCH_SHOW_EPISODE_LIST: "show/FETCH_SHOW_EPISODE_LIST",
  FETCH_SHOW_EPISODE_LIST_SUCCEEDED: "show/FETCH_SHOW_EPISODE_LIST_SUCCEEDED",
  FETCH_SHOW_EPISODE_LIST_FAILED: "show/FETCH_SHOW_EPISODE_LIST_FAILED",

  FETCH_SHOW_EPISODE: "show/FETCH_SHOW_EPISODE",
  FETCH_SHOW_EPISODE_SUCCEEDED: "show/FETCH_SHOW_EPISODE_SUCCEEDED",
  FETCH_SHOW_EPISODE_FAILED: "show/FETCH_SHOW_EPISODE_FAILED",
};
